In [44]:
import numpy as np
import pandas as pd
import scipy.spatial
import math
from scipy.spatial.distance import correlation

In [94]:
a=pd.DataFrame()
num=100

In [95]:
a[1]=list(range(num))

In [96]:
a[2]=[i**2 for i in range(num)]

In [97]:
a[3]=[i**3 for i in range(num)]
a[4]=[math.exp(i+1)+math.log(i+1)+math.sin(i)-i+math.cos(i)+math.sqrt(i) for i in range(num)]
a

     1     2       3             4
0    0     0       0  3.718282e+00
1    1     1       1  9.463977e+00
2    2     4       8  2.109151e+01
3    3     9      27  5.386762e+01
4    4    16      64  1.466122e+02
5    5    25     125  4.017814e+02
6    6    36     216  1.095709e+03
7    7    49     343  2.980094e+03
8    8    64     512  8.100953e+03
9    9    81     729  2.202227e+04
10  10   100    1000  5.986832e+04
11  11   121    1331  1.627486e+05
12  12   144    1728  4.424077e+05
13  13   169    2197  1.202599e+06
14  14   196    2744  3.269011e+06
15  15   225    3375  8.886102e+06
16  16   256    4096  2.415494e+07
17  17   289    4913  6.565996e+07
18  18   324    5832  1.784823e+08
19  19   361    6859  4.851652e+08
20  20   400    8000  1.318816e+09
21  21   441    9261  3.584913e+09
22  22   484   10648  9.744803e+09
23  23   529   12167  2.648912e+10
24  24   576   13824  7.200490e+10
25  25   625   15625  1.957296e+11
26  26   676   17576  5.320482e+11
27  27   729   19683  1.446257e+12
28  28   784   21952  3.931334e+12
29  29   841   24389  1.068647e+13
..  ..   ...     ...           ...
70  70  4900  343000  6.837671e+30
71  71  5041  357911  1.858672e+31
72  72  5184  373248  5.052394e+31
73  73  5329  389017  1.373383e+32
74  74  5476  405224  3.733242e+32
75  75  5625  421875  1.014800e+33
76  76  5776  438976  2.758513e+33
77  77  5929  456533  7.498417e+33
78  78  6084  474552  2.038281e+34
79  79  6241  493039  5.540622e+34
80  80  6400  512000  1.506097e+35
81  81  6561  531441  4.093997e+35
82  82  6724  551368  1.112864e+36
83  83  6889  571787  3.025077e+36
84  84  7056  592704  8.223013e+36
85  85  7225  614125  2.235247e+37
86  86  7396  636056  6.076030e+37
87  87  7569  658503  1.651636e+38
88  88  7744  681472  4.489613e+38
89  89  7921  704969  1.220403e+39
90  90  8100  729000  3.317400e+39
91  91  8281  753571  9.017628e+39
92  92  8464  778688  2.451246e+40
93  93  8649  804357  6.663176e+40
94  94  8836  830584  1.811239e+41
95  95  9025  857375  4.923458e+41
96  96  9216  884736  1.338335e+42
97  97  9409  912673  3.637971e+42
98  98  9604  941192  9.889030e+42
99  99  9801  970299  2.688117e+43

[100 rows x 4 columns]

In [98]:
a.corr()

          1         2         3         4
1  1.000000  0.967644  0.915516  0.252032
2  0.967644  1.000000  0.985950  0.322468
3  0.915516  0.985950  1.000000  0.377615
4  0.252032  0.322468  0.377615  1.000000

In [99]:
a.corr(method='spearman')

     1    2    3    4
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0

In [100]:
correlation(a[1].values ,a[4].values)

0.7479679660961297